Mobile html and css Pull
SSEKA/My-Portfolio pull request #1
Opened 2023-02-21 12:14 UTC by SSEKA

The first pull request after integration of HTML and CSS.

2023-02-21 19:42 UTC, mahbubul14 requested changes
Hi @SSEKA,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Your `README` file is not updated according to the project. Kindly work on it and make it looks professional.

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "Fixed bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-21 19:42 UTC, mahbubul14 commented on index.html
> +            <a class="logo" href="#">My logo</a>
- [ ] You should move this `a` tag outside of the `nav` tag. :+1:

2023-02-21 19:42 UTC, mahbubul14 commented on index.html
> +    </div>
- [ ] Your website should look exactly like the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Kindly fix the background color. :+1: 

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![your](https://user-images.githubusercontent.com/70483835/220441125-b336cac5-0399-41b3-b7a5-7b1d4ed3f82a.png) | ![png](https://user-images.githubusercontent.com/70483835/220440763-f0f336b3-cba4-4d5b-9b5b-f389b1e112b5.png)

2023-02-22 09:32 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @SSEKA, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
-  No linter errors. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 09:32 UTC, Qoosim commented on index.html
> +            <a class="logo" href="#">My logo</a>
- [ ] As requested by the previous reviewer, kindly move `a` tag outside the `nav` tag.

2023-02-22 09:32 UTC, Qoosim commented on README.md
>  <p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] As suggested by the previous reviewer, all the headings on the readme template must be present on your readme file except the FAQ section which is optional. At this moment, some headings are missing from your readme. Such as `Key Features and Future Features` etc. Kindly follow [Microverse template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to make your professional readme.

2023-02-22 09:32 UTC, Qoosim commented on index.html
> +    </div>
- [ ] As mentioned by the previous reviewer, Kindly ensure that your design looks exactly like that of figma design. At this moment, your design is not in line with what we have on the figma design. The Figma Design has white background, but your design does not have the same background and many other differences. Kindly give it a closer look and work your design alongside the figma design.

### Your Design
![your-page](https://user-images.githubusercontent.com/26597432/220579193-28b88406-c23f-4ea1-81fa-c10275b946b1.png)

### Figma Design
![temp-page](https://user-images.githubusercontent.com/26597432/220579258-c66ef092-224f-47bc-841f-41674bce9913.png)

2023-02-23 14:45 UTC, Lizdev-05 requested changes
Hi @SSEKA, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>
 ## Highlights

- [ ] No linter errors. ✔️
- [ ] Correct GitHub Flow. ✔️
- [ ] Descriptive README


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 14:45 UTC, Lizdev-05 commented on index.html
> +      </div>
I think you should be able to achieve the  design by adding a section that will be a wrapper for this bio part, you can give it a class name "main-container" and give it this style 

```
.main-container {
  width: 100%;
  height: 100%;
  z-index: 999;
}
```
Your design presently is not aligned with the Figma design... 😞 

| Your Design | Figma Design |
| :---:   | :---: | 
| <img width="375" alt="image" src="https://user-images.githubusercontent.com/73854999/220939128-f58d535c-f33b-4fae-857b-310af1f31467.png">|<img width="375" alt="image" src="https://user-images.githubusercontent.com/73854999/220939370-b7dd1b13-9953-4f03-8897-cd3f18b553b9.png">|

2023-02-23 14:45 UTC, Lizdev-05 commented on style.css
> +}
Great job making the required changes 👍 . As requested by the previous reviewers, your project design is not in line with the Figma design.

I think you should consider using this styling...

 ```
 width: 100%;
  height: calc(718px - 60px);
 background-image: url(./images/mobile-background-img.png);
  background-position: center;
  background-size: contain;
  background-repeat: no-repeat;
  overflow: hidden;
  border-bottom-left-radius: 5rem;
  background-color: #fff;
  position: relative;
```

2023-02-24 09:33 UTC, Lizdev-05 approved these changes
Hi @SSEKA, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/26gsvAm8UPaczzXz2/giphy.gif"/>
## Highlights

- Correct GitHub Flow 👍

- All linters passed 🏅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 11:42 UTC, merged